name: My Workflow
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Run Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: siddhant660
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Commit and Push Changes
        uses: EndBug/git-pull-request@v4
        with:
          branch: snake-animation
          base: main
          commit-message: Add Snake Animation to GitHub Profile README
          token: ${{ secrets.GITHUB_TOKEN }}

